(defun dlx-search (k)
  (cond ((eq (dlx-right root) root) (dlx-print))
        (t (let ((c (dlx-choose-column)))
             (dlx-cover c)
             (do* ((r (dlx-down c) (dlx-down r))
                   (ok r r))
               ((eq r c))
               (do ((j (dlx-right r) (dlx-right j)))
                 ((eq j r))
                 (dlx-cover j))
               (dlx-search (1+ k))
               (setf r ok)
               (setf c (dlx-header c))
               (do (j (dlx-left r) (dlx-left j))
                 ((eq j r))
                 (dlx-uncover j)))
             (dlx-uncover c)))))
